version: "3"
services:
  nlp-recipes:
    build: .
    volumes:
      - $PWD:/workspace
      - $SSH_AUTH_SOCK:/ssh-agent
    image: nlp-japanese
    container_name: nlp-recipes-ja
    working_dir: /workspace
    ports:
      - 8888:8888
    environment:
      - PYTHONPATH=/workspace
      - SSH_AUTH_SOCK=/ssh-agent
    tty: true
