version: "3"
services:
  nlp-recipes:
    build: .
    volumes:
      - $PWD:/workspace
    container_name: nlp-recipes-ja
    working_dir: /workspace
    ports:
      - 8888:8888
    environment:
      - PYTHONPATH=/workspace
    tty: true
