version: "3"
services:
  test:
    build: .
    volumes:
      - $PWD:/working
    container_name: nlp-recipes-ja
    working_dir: /working
    ports:
      - 8888:8888
    environment:
      - PYTHONPATH=/working
    tty: true
